services:
    base:
     build:
        #   ruta a traves de la cual desde cualquier proyecto, se tiene acceso a
        # â¬‡ cualquier imagen (DockerFile), aqui se marca la ruta absoluta
        context: "/home/renzo/HLC/devops/docker/Caronte"
        dockerfile: "./dockerfiles/base/ubuntu/Dockerfile" # <- apunta al dockerfile
    container_name: "ctbaseDAW"
